"""
train.py
--------
Step 3 & 5 of Day 3: the ONE reusable train/eval harness.

This is the single function every experiment runs through, regardless
of which model is plugged in. It:
  1. loads data (via data.py)
  2. builds features (via features.py)
  3. splits train/test (seeded, from config.py)
  4. fits + evaluates whatever model object it's handed (via model.py)
  5. computes metrics (via evaluate.py)
  6. appends one row to the experiment log (Step 5's "metrics flow to the log")

To run a brand new model tomorrow, you do NOT edit this file.
You write a new class in model.py and pass it into run_experiment().
"""

import os
import datetime
import pandas as pd
from sklearn.model_selection import train_test_split

from config import CONFIG
from data import load_joined_data
from features import build_feature_table
from evaluate import compute_metrics


def run_experiment(model, model_name: str, label_col: str = "is_good_match"):
    """
    The reusable harness. `model` must follow the .fit()/.predict()
    interface defined in model.py — that's the only requirement,
    which is what "interfaces" (Step 5 concept) buys you: this
    function never needs to change when the model changes.
    """
    # 1. Load (data.py's job, not this file's)
    data = load_joined_data()

    # 2. Build features (features.py's job, not this file's)
    data = build_feature_table(data)

    # 3. Reproducible split — seed comes from config, never hard-coded here
    train_data, test_data = train_test_split(
        data,
        test_size=CONFIG["test_size"],
        random_state=CONFIG["seed"],
        stratify=data[label_col],
    )

    # 4. Fit + predict, through the clean model interface
    model.fit(train_data)
    predictions = model.predict(test_data)

    # 5. Evaluate (evaluate.py's job, not this file's)
    metrics = compute_metrics(test_data[label_col], predictions)

    # 6. Log this run so numbers are never lost (Step 5)
    log_experiment(model_name, metrics)

    return metrics


def log_experiment(model_name: str, metrics: dict):
    """
    Appends one row per run to a CSV experiment log, creating it with
    headers if it doesn't exist yet. Every run is now reproducible AND
    recorded — satisfying both Day 1's and Day 3's requirements.
    """
    log_path = CONFIG["experiment_log_path"]
    row = {
        "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
        "model_name": model_name,
        "seed": CONFIG["seed"],
        **metrics,
    }
    row_df = pd.DataFrame([row])

    if os.path.exists(log_path):
        row_df.to_csv(log_path, mode="a", header=False, index=False)
    else:
        row_df.to_csv(log_path, mode="w", header=True, index=False)


if __name__ == "__main__":
    # Demo run: wire the Day 2 baseline through this exact harness.
    # This is Step 4 — "wire the dummy/baseline model through it."
    from model import BaselineSkillOverlapModel

    baseline = BaselineSkillOverlapModel()
    results = run_experiment(baseline, model_name="baseline_skill_overlap")

    print("Experiment complete. Results:")
    for k, v in results.items():
        print(f"  {k}: {v}")
    print(f"\nLogged to: {CONFIG['experiment_log_path']}")
